//! Build-time protobuf + gRPC code generator (zero dependencies).
//!
//! Scans `proto/*.proto` at build time and generates idiomatic Rust
//! (structs + wire codecs + typed gRPC client stubs) into
//! `OUT_DIR/courierust_generated.rs`, which the crate re-exports as
//! `courierust::courierust_grpc::generated`.
//!
//! Supported proto subset:
//!   * `syntax = "proto3";` and `package foo.bar;` (package -> module
//!     nesting)
//!   * `message` with scalar fields (`string bytes bool int32 int64
//!     uint32 uint64 sint32 sint64 fixed32 fixed64 float double`),
//!     `repeated <scalar>`, message-typed fields and `repeated
//!     <Message>`; `//` line comments and `/* */` block comments
//!   * `service` with unary and server-streaming `rpc` methods
//!
//! Field numbers are validated (1..=2^29-1, unique per message). The
//! generated code compiles against the crate's own wire codec
//! (`courierust_grpc::proto`) — no prost, no syn, no third-party crate.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=proto");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let proto_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("proto");
    let mut generated = String::from(
        "// @generated by build.rs from proto/*.proto — do not edit by hand.\n\
         // Uses the crate's own protobuf wire codec; no third-party crates.\n\n",
    );
    if proto_dir.is_dir() {
        let mut entries: Vec<_> = fs::read_dir(&proto_dir)
            .expect("read proto dir")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map(|x| x == "proto").unwrap_or(false))
            .collect();
        entries.sort_by_key(|e| e.file_name());
        for entry in entries {
            let text = fs::read_to_string(entry.path()).expect("read proto file");
            match parse_proto(&text) {
                Ok(file) => generate_file(&mut generated, &file),
                Err(error) => panic!("failed to parse {}: {error}", entry.path().display()),
            }
        }
    }
    let out_path = Path::new(&out_dir).join("courierust_generated.rs");
    fs::write(&out_path, &generated).expect("write generated code");
}

// ---------------------------------------------------------------------
// Proto model
// ---------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
enum FieldType {
    Scalar(&'static str),
    Repeated(&'static str),
    Message(String),
    RepeatedMessage(String),
}

#[derive(Debug)]
struct Field {
    number: u32,
    name: String,
    ty: FieldType,
}

#[derive(Debug)]
struct Message {
    name: String,
    fields: Vec<Field>,
}

#[derive(Debug)]
struct Rpc {
    name: String,
    request: String,
    response: String,
    server_streaming: bool,
}

#[derive(Debug)]
struct Service {
    name: String,
    rpcs: Vec<Rpc>,
}

#[derive(Debug, Default)]
struct ProtoFile {
    package: Option<String>,
    messages: Vec<Message>,
    services: Vec<Service>,
}

// ---------------------------------------------------------------------
// Parser (a small, strict tokenizer for the supported subset)
// ---------------------------------------------------------------------

fn parse_proto(text: &str) -> Result<ProtoFile, String> {
    let mut tokens = tokenize(text)?;
    let mut file = ProtoFile::default();
    while !tokens.is_empty() && !matches!(tokens.first(), Some(Token::Eof)) {
        let (keyword, semicolon) = match tokens.remove(0) {
            Token::Ident(s) => (s, false),
            Token::Semicolon => (String::new(), true),
            other => return Err(format!("expected identifier, got {other:?}")),
        };
        if semicolon {
            continue;
        }
        match keyword.as_str() {
            "syntax" => {
                expect(&mut tokens, Token::Eq, "syntax =")?;
                tokens.remove(0); // the quoted string
                expect(&mut tokens, Token::Semicolon, "syntax ;")?;
            }
            "package" => {
                let mut parts = Vec::new();
                loop {
                    match tokens.remove(0) {
                        Token::Ident(s) => parts.push(s),
                        Token::Dot => {}
                        Token::Semicolon => break,
                        other => return Err(format!("bad package: {other:?}")),
                    }
                }
                file.package = Some(parts.join("."));
            }
            "message" => {
                let name = expect_ident(&mut tokens, "message name")?;
                expect(&mut tokens, Token::LBrace, "message {")?;
                let mut fields = Vec::new();
                loop {
                    match tokens.remove(0) {
                        Token::RBrace => break,
                        Token::Ident(leading) => {
                            // repeated? then the actual type
                            let mut ty_name = leading;
                            let mut repeated = false;
                            if ty_name == "repeated" {
                                repeated = true;
                                ty_name = expect_ident(&mut tokens, "repeated type")?;
                            }
                            let field_name = expect_ident(&mut tokens, "field name")?;
                            expect(&mut tokens, Token::Eq, "field =")?;
                            let number = expect_u32(&mut tokens, "field number")?;
                            if number == 0 || number >= (1 << 29) {
                                return Err(format!("invalid field number {number} in {name}"));
                            }
                            if fields.iter().any(|f: &Field| f.number == number) {
                                return Err(format!(
                                    "duplicate field number {number} in message {name}"
                                ));
                            }
                            expect(&mut tokens, Token::Semicolon, "field ;")?;
                            let ty = if let Some(scalar) = scalar_of(&ty_name) {
                                if repeated {
                                    FieldType::Repeated(scalar)
                                } else {
                                    FieldType::Scalar(scalar)
                                }
                            } else if repeated {
                                FieldType::RepeatedMessage(ty_name)
                            } else {
                                FieldType::Message(ty_name)
                            };
                            fields.push(Field {
                                number,
                                name: field_name,
                                ty,
                            });
                        }
                        other => return Err(format!("bad field: {other:?}")),
                    }
                }
                file.messages.push(Message { name, fields });
            }
            "service" => {
                let name = expect_ident(&mut tokens, "service name")?;
                expect(&mut tokens, Token::LBrace, "service {")?;
                let mut rpcs = Vec::new();
                loop {
                    match tokens.remove(0) {
                        Token::RBrace => break,
                        Token::Ident(word) if word == "rpc" => {
                            let rpc_name = expect_ident(&mut tokens, "rpc name")?;
                            expect(&mut tokens, Token::LParen, "rpc (")?;
                            let request = expect_ident(&mut tokens, "request type")?;
                            expect(&mut tokens, Token::RParen, "rpc )")?;
                            expect(&mut tokens, Token::Ident("returns".to_owned()), "returns")?;
                            expect(&mut tokens, Token::LParen, "returns (")?;
                            let mut server_streaming = false;
                            if matches!(tokens.first(), Some(Token::Ident(w)) if w == "stream") {
                                tokens.remove(0);
                                server_streaming = true;
                            }
                            let response = expect_ident(&mut tokens, "response type")?;
                            expect(&mut tokens, Token::RParen, "returns )")?;
                            expect(&mut tokens, Token::Semicolon, "rpc ;")?;
                            rpcs.push(Rpc {
                                name: rpc_name,
                                request,
                                response,
                                server_streaming,
                            });
                        }
                        other => return Err(format!("bad service item: {other:?}")),
                    }
                }
                file.services.push(Service { name, rpcs });
            }
            "option" | "import" => {
                // Skip to the terminating semicolon (imports and options
                // are not needed by the generator).
                loop {
                    match tokens.remove(0) {
                        Token::Semicolon => break,
                        Token::Eof => return Err("unterminated option/import".to_string()),
                        _ => {}
                    }
                }
            }
            other => return Err(format!("unsupported proto keyword: {other}")),
        }
    }
    Ok(file)
}

fn scalar_of(name: &str) -> Option<&'static str> {
    Some(match name {
        "string" => "string",
        "bytes" => "bytes",
        "bool" => "bool",
        "int32" => "int32",
        "int64" => "int64",
        "uint32" => "uint32",
        "uint64" => "uint64",
        "sint32" => "sint32",
        "sint64" => "sint64",
        "fixed32" => "fixed32",
        "fixed64" => "fixed64",
        "float" => "float",
        "double" => "double",
        _ => return None,
    })
}

// ---------------------------------------------------------------------
// Tokenizer
// ---------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
enum Token {
    Ident(String),
    Eq,
    Dot,
    Semicolon,
    LBrace,
    RBrace,
    LParen,
    RParen,
    /// A quoted string (kept verbatim, including quotes).
    Quoted(String),
    Number(u32),
    Eof,
}

fn tokenize(text: &str) -> Result<Vec<Token>, String> {
    let bytes = text.as_bytes();
    let mut tokens = Vec::new();
    let mut i = 0usize;
    while i < bytes.len() {
        let c = bytes[i] as char;
        if c.is_whitespace() {
            i += 1;
            continue;
        }
        if c == '/' && i + 1 < bytes.len() && bytes[i + 1] as char == '/' {
            while i < bytes.len() && bytes[i] as char != '\n' {
                i += 1;
            }
            continue;
        }
        if c == '/' && i + 1 < bytes.len() && bytes[i + 1] as char == '*' {
            let end = text[i + 2..]
                .find("*/")
                .ok_or_else(|| "unterminated block comment".to_string())?;
            i += 2 + end + 2;
            continue;
        }
        match c {
            '=' => {
                tokens.push(Token::Eq);
                i += 1;
            }
            '.' => {
                tokens.push(Token::Dot);
                i += 1;
            }
            ';' => {
                tokens.push(Token::Semicolon);
                i += 1;
            }
            '{' => {
                tokens.push(Token::LBrace);
                i += 1;
            }
            '}' => {
                tokens.push(Token::RBrace);
                i += 1;
            }
            '(' => {
                tokens.push(Token::LParen);
                i += 1;
            }
            ')' => {
                tokens.push(Token::RParen);
                i += 1;
            }
            '"' | '\'' => {
                let quote = c;
                let start = i + 1;
                let mut end = start;
                while end < bytes.len() && bytes[end] as char != quote {
                    end += 1;
                }
                if end >= bytes.len() {
                    return Err("unterminated string literal".to_string());
                }
                tokens.push(Token::Quoted(text[start..end].to_string()));
                i = end + 1;
            }
            '0'..='9' => {
                let start = i;
                while i < bytes.len() && (bytes[i] as char).is_ascii_digit() {
                    i += 1;
                }
                let value: u32 = text[start..i]
                    .parse()
                    .map_err(|_| "invalid field number".to_string())?;
                tokens.push(Token::Number(value));
            }
            c if c.is_alphabetic() || c == '_' => {
                let start = i;
                while i < bytes.len()
                    && (bytes[i] as char == '_' || (bytes[i] as char).is_alphanumeric())
                {
                    i += 1;
                }
                tokens.push(Token::Ident(text[start..i].to_string()));
            }
            other => return Err(format!("unexpected character `{other}`")),
        }
    }
    tokens.push(Token::Eof);
    Ok(tokens)
}

fn expect(tokens: &mut Vec<Token>, expected: Token, what: &str) -> Result<(), String> {
    if tokens.is_empty() {
        return Err(format!("unexpected end of file while parsing {what}"));
    }
    let actual = tokens.remove(0);
    if actual == expected {
        Ok(())
    } else {
        Err(format!("expected {what}, got {actual:?}"))
    }
}

fn expect_ident(tokens: &mut Vec<Token>, what: &str) -> Result<String, String> {
    match tokens.remove(0) {
        Token::Ident(s) => Ok(s),
        other => Err(format!("expected {what}, got {other:?}")),
    }
}

fn expect_u32(tokens: &mut Vec<Token>, what: &str) -> Result<u32, String> {
    match tokens.remove(0) {
        Token::Number(n) => Ok(n),
        other => Err(format!("expected {what}, got {other:?}")),
    }
}

// ---------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------

fn to_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

fn rust_scalar(name: &str) -> &'static str {
    match name {
        "string" => "alloc::string::String",
        "bytes" => "alloc::vec::Vec<u8>",
        "bool" => "bool",
        "int32" | "sint32" => "i32",
        "int64" | "sint64" => "i64",
        "uint32" | "fixed32" => "u32",
        "uint64" | "fixed64" => "u64",
        "float" => "f32",
        "double" => "f64",
        _ => unreachable!("scalar"),
    }
}

fn rust_scalar_f32_f64(name: &str) -> &'static str {
    rust_scalar(name)
}

fn generate_file(out: &mut String, file: &ProtoFile) {
    // Nest under the package, if any.
    if let Some(package) = &file.package {
        let parts: Vec<&str> = package.split('.').collect();
        let mut full_pkg = String::new();
        for (i, part) in parts.iter().enumerate() {
            if i > 0 {
                full_pkg.push('.');
            }
            full_pkg.push_str(part);
        }
        for part in &parts {
            out.push_str(&format!(
                "/// Proto package `{full_pkg}` (generated).\npub mod {part} {{\n"
            ));
        }
        out.push_str("    use crate::courierust_grpc::proto;\n");
        out.push_str("    use crate::courierust_grpc::proto::ProtoMessage;\n");
        out.push_str("    use crate::courierust_grpc::codec;\n");
        out.push_str("    use crate::courierust_error::{Error, Result};\n");
        for message in &file.messages {
            generate_message(out, message, 1);
        }
        for service in &file.services {
            generate_service(out, service, 1, file.package.as_deref());
        }
        for _ in &parts {
            out.push_str("}\n");
        }
    } else {
        out.push_str("use crate::courierust_grpc::proto;\n");
        out.push_str("use crate::courierust_grpc::proto::ProtoMessage;\n");
        out.push_str("use crate::courierust_grpc::codec;\n");
        out.push_str("use crate::courierust_error::{Error, Result};\n");
        for message in &file.messages {
            generate_message(out, message, 0);
        }
        for service in &file.services {
            generate_service(out, service, 0, file.package.as_deref());
        }
    }
}

fn indent(level: usize) -> String {
    "    ".repeat(level)
}

/// The wire "kind" used in helper names for a scalar (distinct from the
/// proto type name, which also covers `string`/`bytes`).
fn scalar_kind(name: &str) -> &'static str {
    match name {
        "bool" => "bool",
        "int32" => "i32",
        "int64" => "i64",
        "uint32" => "u32",
        "uint64" => "u64",
        "sint32" => "s32",
        "sint64" => "s64",
        "fixed32" => "fixed32",
        "fixed64" => "fixed64",
        "float" => "float",
        "double" => "double",
        _ => unreachable!("{name} is not a scalar"),
    }
}

/// Whether a scalar is length-delimited (`string`/`bytes`).
fn is_length_delimited(name: &str) -> bool {
    name == "string" || name == "bytes"
}

fn generate_message(out: &mut String, message: &Message, level: usize) {
    let ind = indent(level);
    // Struct.
    out.push_str(&format!(
        "\n{ind}/// Message `{}` (proto3).\n",
        message.name
    ));
    out.push_str(&format!(
        "{ind}#[derive(Debug, Clone, PartialEq, Default)]\n"
    ));
    out.push_str(&format!("{ind}pub struct {} {{\n", message.name));
    for field in &message.fields {
        let rust_ty = match &field.ty {
            FieldType::Scalar(s) => rust_scalar_f32_f64(s).to_string(),
            FieldType::Repeated(s) => {
                format!("alloc::vec::Vec<{}>", rust_scalar_f32_f64(s))
            }
            FieldType::Message(m) => format!("::core::option::Option<{m}>"),
            FieldType::RepeatedMessage(m) => format!("alloc::vec::Vec<{m}>"),
        };
        out.push_str(&format!(
            "{ind}    /// Field {} (`{}`).\n",
            field.number, field.name
        ));
        out.push_str(&format!("{ind}    pub {}: {rust_ty},\n", field.name));
    }
    out.push_str(&format!("{ind}}}\n"));

    // ProtoMessage encode.
    out.push_str(&format!(
        "\n{ind}impl proto::ProtoMessage for {} {{\n",
        message.name
    ));
    out.push_str(&format!(
        "{ind}    fn encode_message_body(&self, out: &mut alloc::vec::Vec<u8>) {{\n"
    ));
    for field in &message.fields {
        let e = indent(level + 2);
        let n = field.number;
        match &field.ty {
            FieldType::Scalar(s) => {
                // string/bytes are passed by reference; Copy scalars by
                // value (the Encoder mirrors the wire type).
                let expr = if is_length_delimited(s) {
                    format!("&self.{}", field.name)
                } else {
                    format!("self.{}", field.name)
                };
                out.push_str(&format!("{e}proto::Encoder::{s}(out, {n}, {expr});\n"));
            }
            FieldType::Message(m) => out.push_str(&format!(
                "{e}if let Some(value) = &self.{} {{ proto::Encoder::message::<{m}>(out, {n}, value); }}\n",
                field.name
            )),
            FieldType::Repeated(s) if is_length_delimited(s) => out.push_str(&format!(
                "{e}for value in &self.{} {{ proto::Encoder::{s}(out, {n}, value); }}\n",
                field.name
            )),
            FieldType::Repeated(s) => {
                let kind = scalar_kind(s);
                out.push_str(&format!(
                    "{e}if !self.{}.is_empty() {{\n\
                     {e}    let mut payload = alloc::vec::Vec::new();\n\
                     {e}    for value in &self.{} {{ proto::push_packed_{kind}(&mut payload, *value); }}\n\
                     {e}    proto::encode_packed_payload(out, {n}, &payload);\n\
                     {e}}}\n",
                    field.name, field.name
                ));
            }
            FieldType::RepeatedMessage(m) => out.push_str(&format!(
                "{e}for value in &self.{} {{ proto::Encoder::message::<{m}>(out, {n}, value); }}\n",
                field.name
            )),
        }
    }
    out.push_str(&format!("{ind}    }}\n"));

    // ProtoMessage decode.
    out.push_str(&format!(
        "{ind}    fn decode_message_body(buf: &[u8]) -> Result<Self> {{\n"
    ));
    out.push_str(&format!("{ind}        let mut result = Self::default();\n"));
    out.push_str(&format!(
        "{ind}        let mut reader = proto::SliceReader::new(buf);\n"
    ));
    out.push_str(&format!("{ind}        while reader.remaining() > 0 {{\n"));
    out.push_str(&format!(
        "{ind}            proto::Decoder::field(&mut reader, |number, wire, value, payload| {{\n"
    ));
    out.push_str(&format!("{ind}                let _ = value;\n"));
    out.push_str(&format!("{ind}                match (number, wire) {{\n"));
    for field in &message.fields {
        let e = indent(level + 4);
        let n = field.number;
        let f = &field.name;
        match &field.ty {
            FieldType::Scalar(s) => {
                if is_length_delimited(s) {
                    if *s == "string" {
                        out.push_str(&format!(
                            "{e}({n}, proto::WireType::LengthDelimited) => {{\n\
                             {e}    result.{f} = ::core::str::from_utf8(payload)\n\
                             {e}        .map_err(|_| Error::protocol(\"invalid utf8 in protobuf string\"))?\n\
                             {e}        .to_string();\n\
                             {e}}}\n"
                        ));
                    } else {
                        out.push_str(&format!(
                            "{e}({n}, proto::WireType::LengthDelimited) => {{\n\
                             {e}    result.{f} = payload.to_vec();\n\
                             {e}}}\n"
                        ));
                    }
                } else {
                    let wire = match *s {
                        "fixed32" | "float" => "proto::WireType::Fixed32",
                        "fixed64" | "double" => "proto::WireType::Fixed64",
                        _ => "proto::WireType::Varint",
                    };
                    let kind = scalar_kind(s);
                    out.push_str(&format!(
                        "{e}({n}, {wire}) => {{\n\
                         {e}    result.{f} = proto::conv_{kind}(value);\n\
                         {e}}}\n"
                    ));
                }
            }
            FieldType::Message(m) => out.push_str(&format!(
                "{e}({n}, proto::WireType::LengthDelimited) => {{\n\
                 {e}    result.{f} = Some(proto::decode_sub_message::<{m}>(payload)?);\n\
                 {e}}}\n"
            )),
            FieldType::Repeated(s) if *s == "string" => out.push_str(&format!(
                "{e}({n}, proto::WireType::LengthDelimited) => {{\n\
                 {e}    result.{f}.push(\n\
                 {e}        ::core::str::from_utf8(payload)\n\
                 {e}            .map_err(|_| Error::protocol(\"invalid utf8 in protobuf string\"))?\n\
                 {e}            .to_string(),\n\
                 {e}    );\n\
                 {e}}}\n"
            )),
            FieldType::Repeated(s) if *s == "bytes" => out.push_str(&format!(
                "{e}({n}, proto::WireType::LengthDelimited) => {{\n\
                 {e}    result.{f}.push(payload.to_vec());\n\
                 {e}}}\n"
            )),
            FieldType::Repeated(s) => {
                let kind = scalar_kind(s);
                // Accept both packed (LengthDelimited) and unpacked
                // (per-element wire type) encodings.
                let element_wire = match *s {
                    "fixed32" | "float" => "proto::WireType::Fixed32",
                    "fixed64" | "double" => "proto::WireType::Fixed64",
                    _ => "proto::WireType::Varint",
                };
                out.push_str(&format!(
                    "{e}({n}, proto::WireType::LengthDelimited) => {{\n\
                     {e}    for v in proto::decode_packed_{kind}(payload)? {{\n\
                     {e}        result.{f}.push(v);\n\
                     {e}    }}\n\
                     {e}}}\n\
                     {e}({n}, {element_wire}) => {{\n\
                     {e}    result.{f}.push(proto::conv_{kind}(value));\n\
                     {e}}}\n"
                ));
            }
            FieldType::RepeatedMessage(m) => out.push_str(&format!(
                "{e}({n}, proto::WireType::LengthDelimited) => {{\n\
                 {e}    result.{f}.push(proto::decode_sub_message::<{m}>(payload)?);\n\
                 {e}}}\n"
            )),
        }
    }
    out.push_str(&format!("{ind}                    _ => {{}}\n"));
    out.push_str(&format!("{ind}                }}\n"));
    out.push_str(&format!("{ind}                Ok(())\n"));
    out.push_str(&format!("{ind}            }})?;\n"));
    out.push_str(&format!("{ind}        }}\n"));
    out.push_str(&format!("{ind}        Ok(result)\n"));
    out.push_str(&format!("{ind}    }}\n"));
    out.push_str(&format!("{ind}}}\n"));

    // Codec trait impls.
    out.push_str(&format!(
        "\n{ind}impl codec::EncodeMessage for {} {{\n",
        message.name
    ));
    out.push_str(&format!(
        "{ind}    fn encode_message(&self) -> Result<alloc::vec::Vec<u8>> {{\n\
         {ind}        let mut out = alloc::vec::Vec::new();\n\
         {ind}        self.encode_message_body(&mut out);\n\
         {ind}        Ok(out)\n\
         {ind}    }}\n\
         {ind}}}\n"
    ));
    out.push_str(&format!(
        "\n{ind}impl codec::DecodeMessage for {} {{\n",
        message.name
    ));
    out.push_str(&format!(
        "{ind}    fn decode_message(bytes: &[u8]) -> Result<Self> {{\n\
         {ind}        Self::decode_message_body(bytes)\n\
         {ind}    }}\n\
         {ind}}}\n"
    ));
}

fn generate_service(out: &mut String, service: &Service, level: usize, package: Option<&str>) {
    let ind = indent(level);
    let qualified = match package {
        Some(pkg) => format!("/{pkg}.{}", service.name),
        None => format!("/{}", service.name),
    };
    let path = qualified.clone();
    out.push_str(&format!(
        "\n{ind}/// Generated gRPC client stub for service `{}`.\n",
        service.name
    ));
    out.push_str(&format!(
        "{ind}#[derive(Clone)]\n{ind}pub struct {} {{\n{ind}    inner: crate::courierust_grpc::GrpcClient,\n{ind}}}\n",
        service.name
    ));
    out.push_str(&format!("\n{ind}impl {} {{\n", service.name));
    out.push_str(&format!(
        "{ind}    /// Create a typed client stub bound to a gRPC connection.\n\
         {ind}    pub fn new(client: crate::courierust_grpc::GrpcClient) -> Self {{\n\
         {ind}        Self {{ inner: client }}\n\
         {ind}    }}\n"
    ));
    out.push_str(&format!(
        "{ind}    /// The fully-qualified service name.\n\
         {ind}    pub fn service_path(&self) -> &'static str {{\n\
         {ind}        \"{path}\"\n\
         {ind}    }}\n"
    ));
    for rpc in &service.rpcs {
        let method = to_snake(&rpc.name);
        let full = format!("{path}/{}", rpc.name);
        if rpc.server_streaming {
            out.push_str(&format!(
                "\n{ind}    /// Server-streaming RPC `{full}`: returns a stream of `{}` messages.\n\
                 {ind}    pub fn {method}(&self, request: {}) -> Result<crate::courierust_grpc::MessageStream> {{\n\
                 {ind}        let bytes = codec::EncodeMessage::encode_message(&request)?;\n\
                 {ind}        self.inner.call_stream(\"{full}\", bytes.into())\n\
                 {ind}    }}\n",
                rpc.response, rpc.request
            ));
        } else {
            out.push_str(&format!(
                "\n{ind}    /// Unary RPC `{full}`.\n\
                 {ind}    pub fn {method}(&self, request: {}) -> Result<{}> {{\n\
                 {ind}        self.inner.call_unary(\"{full}\", &request)\n\
                 {ind}    }}\n",
                rpc.request, rpc.response
            ));
        }
    }
    out.push_str(&format!("{ind}}}\n"));
}
